export const WEEKDAYS = [
  ["monday", "周一"],
  ["tuesday", "周二"],
  ["wednesday", "周三"],
  ["thursday", "周四"],
  ["friday", "周五"],
  ["saturday", "周六"],
  ["sunday", "周日"],
];

export const WEEKDAY_LABELS = Object.fromEntries(WEEKDAYS);

export const DAY_ALIASES = new Map([
  ["monday", "monday"],
  ["mon", "monday"],
  ["周一", "monday"],
  ["星期一", "monday"],
  ["礼拜一", "monday"],
  ["tuesday", "tuesday"],
  ["tue", "tuesday"],
  ["周二", "tuesday"],
  ["星期二", "tuesday"],
  ["礼拜二", "tuesday"],
  ["wednesday", "wednesday"],
  ["wed", "wednesday"],
  ["周三", "wednesday"],
  ["星期三", "wednesday"],
  ["礼拜三", "wednesday"],
  ["thursday", "thursday"],
  ["thu", "thursday"],
  ["周四", "thursday"],
  ["星期四", "thursday"],
  ["礼拜四", "thursday"],
  ["friday", "friday"],
  ["fri", "friday"],
  ["周五", "friday"],
  ["星期五", "friday"],
  ["礼拜五", "friday"],
  ["saturday", "saturday"],
  ["sat", "saturday"],
  ["周六", "saturday"],
  ["星期六", "saturday"],
  ["礼拜六", "saturday"],
  ["sunday", "sunday"],
  ["sun", "sunday"],
  ["周日", "sunday"],
  ["周天", "sunday"],
  ["星期日", "sunday"],
  ["星期天", "sunday"],
  ["礼拜日", "sunday"],
  ["礼拜天", "sunday"],
]);

export const TEMPLATE_LABELS = {
  random: "随机",
  regular: "常规",
  sprint: "冲刺",
  relax: "放松",
  social: "社交",
  recovery: "恢复",
  holiday: "假期",
  study: "学习",
  gaming: "游戏",
};

export const TIME_PERIOD_LABELS = {
  dawn: "凌晨",
  morning: "早晨",
  forenoon: "上午",
  noon: "中午",
  afternoon: "下午",
  evening: "傍晚",
  night: "晚上",
  late_night: "深夜",
};

export const LIFE_MODE_LABELS = {
  awake: "清醒",
  sleeping: "睡眠中",
  late_night: "熬夜",
  all_nighter: "通宵",
  resting: "休息",
  relax: "放松",
  relaxing: "放松",
  going_out: "外出",
  mixed: "混合节奏",
};

export const SCHEDULE_TONE_LABELS = {
  ...LIFE_MODE_LABELS,
  awake: "正常活动",
  sleeping: "低活动休息",
  late_night: "夜间清醒",
  all_nighter: "通宵节奏",
  resting: "低强度休息",
  going_out: "外出节奏",
};

export const SLEEP_MODE_LABELS = {
  normal: "正常睡眠",
  late_night: "熬夜",
  all_nighter: "通宵",
  nap: "小睡",
  early_sleep: "早睡",
  awake: "清醒",
  asleep: "已入睡",
  mixed: "混合",
};

export const SLEEP_DEPTH_LABELS = {
  awake: "清醒",
  light_rest: "浅休息",
  light_sleep: "浅睡眠",
  deep_sleep: "深度睡眠",
};

export const CURRENT_SLEEP_LABELS = {
  ...SLEEP_DEPTH_LABELS,
  awake: "未入睡",
};

export const SCHEDULE_INTENT_LABELS = {
  home: "居家",
  work: "工作",
  study: "学习",
  social: "社交",
  rest: "休息",
  relax: "放松",
  relaxing: "放松",
  outing: "外出",
  mixed: "混合安排",
  active: "活跃",
  normal: "常规",
};

export const OUTFIT_DECISION_LABELS = {
  keep: "保持当前穿搭",
  keep_current: "保持当前穿搭",
  unchanged: "不更换",
  update: "更新穿搭",
  change: "更换穿搭",
  partial_change: "局部调整",
  half_change: "局部调整",
  adjust: "局部调整",
  outdoor: "外出",
  switch_home: "换成居家状态",
  switch_outdoor: "换成外出状态",
  sleepwear: "换成睡眠/居家穿搭",
  sleep: "进入睡眠状态",
  late_night: "熬夜状态",
  all_nighter: "通宵状态",
  unknown: "未知",
};

export const PLAN_OUTFIT_DECISION_LABELS = {
  ...OUTFIT_DECISION_LABELS,
  keep: "预计保持",
  keep_current: "预计保持",
  unchanged: "预计不更换",
  update: "预计更新",
  change: "预计更换",
  partial_change: "预计局部调整",
  half_change: "预计局部调整",
  adjust: "预计局部调整",
  outdoor: "预计外出",
  switch_home: "预计居家",
  switch_outdoor: "预计外出",
  sleepwear: "预计睡眠/居家",
  sleep: "预计睡眠",
  late_night: "预计夜间状态",
  all_nighter: "预计通宵状态",
};

export const SOURCE_LABELS = {
  daily: "每日生成",
  context: "上下文刷新",
  chat: "聊天触发",
  manual: "手动刷新",
  dashboard: "面板刷新",
  idle: "自动刷新",
  invite: "邀约",
  command: "指令",
  memo: "备忘录",
  commitment: "承诺",
  chat_memory: "聊天记忆",
  daily_review: "每日复盘",
  life_event: "生活事件",
  learning: "偏好学习",
  custom: "自定义",
  builtin: "内置",
  event: "事件",
  observation: "观察",
  daily_generation: "每日生成",
  episode: "生活片段",
  memory: "记忆",
  state: "状态",
  auto: "自动刷新",
  weather: "天气",
  user: "用户",
  system: "系统",
};

export const PAGE_STATUS_REASON_LABELS = {
  state: "实时状态更新",
  daily_refresh: "每日生活背景刷新",
  nightly_review: "夜间复盘",
  weekly_refresh: "每周生活主题刷新",
  weather: "天气更新",
  autonomous_life_update: "自主生活状态与穿搭更新",
  invite_outfit_update: "邀约后的穿搭判断",
  private_revisit: "私聊回访",
  proactive_reply: "闲时回复",
  proactive_reply_decision: "闲时回复裁定",
  expression_decision: "表达方式裁定",
};

export const VISIBILITY_LABELS = {
  unseen: "未看见",
  scanned: "扫到",
  seen_but_ignored: "看见但略过",
  seen: "已留意",
  focused: "重点留意",
  skimmed: "粗略看过",
  ignored: "已忽略",
  missed: "未注意",
};

export const FRESHNESS_LABELS = {
  fresh: "新鲜",
  recent: "较近",
  stale: "过期",
  old: "旧消息",
  reactivated: "重新激活",
  renewed: "重新变新",
  ignored: "已忽略",
  seen: "已看见",
  unknown: "未知",
};

export const PREFERENCE_CATEGORY_LABELS = {
  activity: "活动",
  outfit: "穿搭",
  social: "社交",
  sleep: "睡眠",
  place: "地点",
  style: "风格",
  other: "其他",
  general: "综合",
};

export const TARGET_TYPE_LABELS = {
  topic: "话题",
  user: "用户",
  person: "人物",
  relationship: "关系",
  group: "群聊",
  session: "会话",
  message: "消息",
  action: "动作",
  behavior: "行为",
  place: "地点",
  event: "事件",
  life_event: "生活事件",
  life_episode: "生活片段",
  daily: "每日记录",
  daily_plan: "日程规划",
  outfit: "穿搭",
  sleep: "睡眠",
  state: "状态",
  memory: "记忆",
  preference: "偏好",
  term: "场景词",
  boundary: "记忆边界",
  other: "其他",
};

export const EVIDENCE_TYPE_LABELS = {
  observation: "观察证据",
  daily_generation: "每日生成依据",
  episode: "生活片段证据",
  chat_memory: "聊天记忆证据",
  relationship: "关系证据",
  behavior_feedback: "行为反馈证据",
  focus_target: "关注目标证据",
  correction: "修正证据",
  review: "复盘证据",
  manual: "手动记录",
  memory: "记忆证据",
  source: "来源证据",
  other: "其他证据",
};

export const PLACE_TYPE_LABELS = {
  place: "地点",
  home: "家",
  cafe: "咖啡店",
  shop: "商店",
  mall: "商场",
  school: "学校",
  office: "办公室",
  workplace: "工作地点",
  park: "公园",
  transit: "交通点",
  neighborhood: "附近街区",
  restaurant: "餐厅",
  cinema: "影院",
  museum: "展馆",
  gym: "健身场所",
  library: "图书馆",
  other: "其他地点",
};

export const SCOPE_LABELS = {
  global: "全局",
  general: "通用",
  group: "群聊",
  private: "私聊",
  session: "会话",
  user: "用户",
  relationship: "关系",
  topic: "话题",
  memory: "记忆",
  current_group: "当前群聊",
  current_session: "当前会话",
  other: "其他",
};

export const HEALTH_CHECK_LABELS = {
  episodes: "生活片段",
  evidence: "证据链",
  focus: "关注目标",
  feedback: "行为反馈",
  terms: "场景词",
  boundaries: "记忆边界",
  memory_rows: "记忆存储",
  relationships: "关系档案",
  places: "地点档案",
  events: "事件记忆",
  chat_summaries: "会话摘要",
  group_environments: "群聊环境",
  message_visibility: "消息留意",
  action_decisions: "动作裁定",
  life_episodes: "生活片段",
  memory_evidence: "记忆证据",
  behavior_feedback: "行为反馈",
  focus_targets: "关注目标",
  life_terms: "场景词",
  memory_boundaries: "记忆边界",
  preferences: "长期偏好",
  life_events: "生活事件",
};

export const CATALOG_CATEGORY_LABELS = {
  daily_themes: "今日主题",
  mood_colors: "心情色彩",
  outfit_styles: "外出穿搭",
  sleep_styles: "居家穿搭",
  schedule_types: "日程类型",
  night_hairstyles: "夜间发型",
};

export const STORAGE_CATEGORY_LABELS = {
  daily: "日常记录",
  memory: "世界记忆",
  planning: "计划安排",
  review: "日常复盘",
  workshop: "素材工坊",
};

export const EVENT_STATUS_LABELS = {
  open: "进行中",
  done: "已完成",
  closed: "已关闭",
  cancelled: "已取消",
  expired: "已过期",
  active: "进行中",
  scheduled: "已计划",
};

export const EPISODE_KIND_LABELS = {
  daily: "每日",
  daily_plan: "日程规划",
  chat: "聊天",
  group: "群聊",
  relationship: "关系",
  outing: "外出",
  decision: "决策",
  mood: "心情",
  other: "其他",
};

export const EPISODE_STATUS_LABELS = {
  open: "进行中",
  done: "已完成",
  closed: "已关闭",
  cancelled: "已取消",
  expired: "已过期",
  corrected: "已修正",
  active: "进行中",
};

export const BOUNDARY_POLICY_LABELS = {
  allow: "允许",
  deny: "禁止",
  ask: "谨慎询问",
};

export const FEEDBACK_RESULT_LABELS = {
  positive: "正向",
  neutral: "中性",
  negative: "负向",
  unknown: "未知",
};

export const ACTION_LABELS = {
  ignore: "忽略",
  reply: "回复",
  observe: "观察",
  remember: "记录",
  save: "保存",
  save_memory: "保存记忆",
  skip_memory: "跳过记忆",
  need_deep_analysis: "需要深度分析",
  voice_expression: "表达方式：语音",
  text_expression: "表达方式：文字",
  deep_analysis: "深度分析",
  watch: "观察",
  watch_only: "仅观察",
  skim: "扫读",
  reactivate: "重新激活",
  defer: "延后",
  comfort: "安抚",
  push_back: "反驳",
  join_ritual: "跟仪式",
  eat_melon: "吃瓜围观",
  interrupt: "打断",
  no_reply: "不回复",
  proactive_reply: "闲时回复",
  proactive_observe: "主动观察",
  proactive_wait: "主动等待",
  proactive_skip: "主动略过",
  none: "无动作",
};

export const UNDERSTANDING_LABELS = {
  understood: "已理解",
  partial: "部分理解",
  unclear: "不明确",
  unknown: "未知",
};

export const SCENE_TYPE_LABELS = {
  chat: "普通闲聊",
  casual: "普通闲聊",
  casual_chat: "普通闲聊",
  profile: "群友档案",
  relationship: "群友档案",
  group_profile: "群友档案",
  environment: "群环境",
  group_environment: "群环境",
  invite: "邀约线索",
  invitation: "邀约线索",
  conflict: "争论",
  argument: "争论",
  meme: "玩梗",
  joke: "玩梗",
  welcome: "欢迎",
  spam: "刷屏",
  repetition: "复读",
  eat_melon: "吃瓜",
  discussing_bot: "提到我",
  other: "其他",
};

export const BOT_WATCH_STATE_LABELS = {
  blackout: "未关注",
  peek: "偶尔看一眼",
  skim_window: "窗口扫读",
  active_watch: "持续关注",
  engaged: "已参与",
};

export const INTERRUPT_LEVEL_LABELS = {
  ordinary: "普通消息可打断",
  medium: "中等相关才打断",
  high: "强信号才打断",
};

export const ATMOSPHERE_LABELS = {
  quiet: "冷清",
  calm: "平稳",
  normal: "平稳",
  active: "活跃",
  busy: "活跃",
  spam: "刷屏",
  argument: "争论",
  conflict: "争论",
  meme: "玩梗",
  joke: "玩梗",
  welcome: "欢迎",
  other: "其他",
};

export const STORAGE_TABLE_LABELS = {
  days: "每日记录",
  timelines: "时间轴",
  outfit_history: "穿搭历史",
  day_meta: "生活标签",
  states: "实时状态",
  state_logs: "状态日志",
  day_places: "当日地点",
  day_events: "当日事件",
  day_event_people: "事件人物",
  relationships: "关系档案",
  relationship_notes: "关系备注",
  relationship_points: "关系记忆点",
  places: "地点档案",
  events: "事件记忆",
  event_people: "事件人物",
  chat_summaries: "会话摘要",
  chat_summary_people: "摘要人物",
  group_environments: "群聊环境",
  message_visibility: "消息留意",
  action_decisions: "动作裁定",
  preferences: "长期偏好",
  life_events: "生活事件",
  life_episodes: "生活片段",
  life_episode_people: "片段人物",
  life_episode_places: "片段地点",
  memory_evidence: "记忆证据",
  behavior_feedback: "行为反馈",
  focus_targets: "关注目标",
  life_terms: "场景词",
  memory_boundaries: "记忆边界",
  week_plans: "周计划",
  week_goals: "周目标",
  week_hints: "周提示",
  week_suggestions: "周建议",
  commitments: "未来承诺",
  commitment_people: "承诺人物",
  day_commitments: "当日承诺",
  daily_reviews: "每日复盘",
  daily_review_points: "复盘要点",
  review_preferences: "复盘偏好",
  custom_catalog_items: "自定义素材",
  custom_hair_styles: "自定义发型组",
  custom_hair_options: "发型选项",
  builtin_item_states: "内置素材状态",
  custom_week_templates: "自定义周模板",
  custom_week_template_goals: "模板目标",
  custom_week_template_hints: "模板提示",
  custom_week_template_suggestions: "模板建议",
  custom_week_template_tags: "模板标签",
};
