export const WEEKDAYS = [
  ["monday", "周一"],
  ["tuesday", "周二"],
  ["wednesday", "周三"],
  ["thursday", "周四"],
  ["friday", "周五"],
  ["saturday", "周六"],
  ["sunday", "周日"],
];

export const WEEKDAY_LABELS = Object.fromEntries(WEEKDAYS);

export const DAY_ALIASES = new Map([
  ["monday", "monday"],
  ["mon", "monday"],
  ["周一", "monday"],
  ["星期一", "monday"],
  ["礼拜一", "monday"],
  ["tuesday", "tuesday"],
  ["tue", "tuesday"],
  ["周二", "tuesday"],
  ["星期二", "tuesday"],
  ["礼拜二", "tuesday"],
  ["wednesday", "wednesday"],
  ["wed", "wednesday"],
  ["周三", "wednesday"],
  ["星期三", "wednesday"],
  ["礼拜三", "wednesday"],
  ["thursday", "thursday"],
  ["thu", "thursday"],
  ["周四", "thursday"],
  ["星期四", "thursday"],
  ["礼拜四", "thursday"],
  ["friday", "friday"],
  ["fri", "friday"],
  ["周五", "friday"],
  ["星期五", "friday"],
  ["礼拜五", "friday"],
  ["saturday", "saturday"],
  ["sat", "saturday"],
  ["周六", "saturday"],
  ["星期六", "saturday"],
  ["礼拜六", "saturday"],
  ["sunday", "sunday"],
  ["sun", "sunday"],
  ["周日", "sunday"],
  ["周天", "sunday"],
  ["星期日", "sunday"],
  ["星期天", "sunday"],
  ["礼拜日", "sunday"],
  ["礼拜天", "sunday"],
]);

export const TIME_PERIOD_LABELS = {
  dawn: "凌晨",
  morning: "早晨",
  forenoon: "上午",
  noon: "中午",
  afternoon: "下午",
  evening: "傍晚",
  night: "晚上",
  late_night: "深夜",
};

export const LIFE_MODE_LABELS = {
  awake: "清醒",
  sleeping: "睡眠中",
  late_night: "熬夜",
  all_nighter: "通宵",
  resting: "休息",
  relax: "放松",
  relaxing: "放松",
  going_out: "外出",
  mixed: "混合节奏",
};

export const SCHEDULE_TONE_LABELS = {
  ...LIFE_MODE_LABELS,
  awake: "正常活动",
  sleeping: "低活动休息",
  late_night: "夜间清醒",
  all_nighter: "通宵节奏",
  resting: "低强度休息",
  going_out: "外出节奏",
};

export const SLEEP_MODE_LABELS = {
  normal: "正常睡眠",
  late_night: "熬夜",
  all_nighter: "通宵",
  nap: "小睡",
  early_sleep: "早睡",
  awake: "清醒",
  asleep: "已入睡",
  mixed: "混合",
};

export const SLEEP_DEPTH_LABELS = {
  awake: "清醒",
  light_rest: "浅休息",
  light_sleep: "浅睡眠",
  deep_sleep: "深度睡眠",
};

export const CURRENT_SLEEP_LABELS = {
  ...SLEEP_DEPTH_LABELS,
  awake: "未入睡",
};

export const SCHEDULE_INTENT_LABELS = {
  home: "居家",
  work: "工作",
  study: "学习",
  social: "社交",
  rest: "休息",
  relax: "放松",
  relaxing: "放松",
  outing: "外出",
  mixed: "混合安排",
  active: "活跃",
  normal: "常规",
};

export const OUTFIT_DECISION_LABELS = {
  keep: "保持当前穿搭",
  keep_current: "保持当前穿搭",
  unchanged: "不更换",
  update: "更新穿搭",
  change: "更换穿搭",
  partial_change: "局部调整",
  half_change: "局部调整",
  adjust: "局部调整",
  outdoor: "外出",
  switch_home: "换成居家状态",
  switch_outdoor: "换成外出状态",
  sleepwear: "换成睡眠/居家穿搭",
  sleep: "进入睡眠状态",
  late_night: "熬夜状态",
  all_nighter: "通宵状态",
  unknown: "未知",
};

export const PLAN_OUTFIT_DECISION_LABELS = {
  ...OUTFIT_DECISION_LABELS,
  keep: "预计保持",
  keep_current: "预计保持",
  unchanged: "预计不更换",
  update: "预计更新",
  change: "预计更换",
  partial_change: "预计局部调整",
  half_change: "预计局部调整",
  adjust: "预计局部调整",
  outdoor: "预计外出",
  switch_home: "预计居家",
  switch_outdoor: "预计外出",
  sleepwear: "预计睡眠/居家",
  sleep: "预计睡眠",
  late_night: "预计夜间状态",
  all_nighter: "预计通宵状态",
};

export const OUTFIT_SCENE_CATEGORY_LABELS = {
  home: "居家",
  sleep: "睡眠/休息",
  outdoor: "户外",
  public: "公共场合",
  mixed: "混合场景",
};

export const OUTFIT_STYLE_POOL_LABELS = {
  sleep_styles: "居家/睡眠风格",
  outfit_styles: "日常/外出风格",
  mixed: "混合风格",
};

export const SOURCE_LABELS = {
  daily: "每日生成",
  daily_generation: "每日生成",
  daily_refresh: "每日刷新",
  context: "上下文刷新",
  chat: "聊天触发",
  chat_batch: "会话批次",
  chat_memory_batch: "聊天记忆批次",
  chat_memory_target: "聊天记忆对象",
  manual: "手动刷新",
  dashboard: "面板刷新",
  dashboard_reset: "面板重置",
  idle: "自动刷新",
  auto: "自动刷新",
  auto_check: "自动检查",
  invite: "邀约",
  invite_tool: "邀约工具",
  command: "指令",
  command_reset: "指令重置",
  memo: "备忘录",
  commitment: "承诺",
  chat_memory: "聊天记忆",
  daily_review: "每日复盘",
  life_event: "生活事件",
  life_adjustment: "生活纠偏",
  learning: "偏好学习",
  custom: "自定义",
  builtin: "内置",
  config: "配置",
  event: "事件",
  observation: "观察",
  autonomous_life: "自主生活",
  episode: "生活片段",
  life_decision: "生活决策",
  action_decision: "动作裁定",
  proactive_reply: "闲时回复",
  proactive: "主动触发",
  proactive_feedback: "主动回复反馈",
  private_revisit: "私聊回访",
  regular_reply: "普通回复",
  reply_effect: "回复效果",
  memory: "记忆",
  state: "状态",
  weather: "天气",
  user: "用户",
  system: "系统",
  startup_seed: "首次启动补全",
  injection_seed: "聊天前补全",
  outfit_seed: "初始穿搭",
  direct: "直接处理",
  fallback: "默认回退",
  natural: "自然分段",
  natural_fallback: "自然分段回退",
  semantic: "语义分段",
  tool: "工具调用",
  tool_preface: "工具前置回复",
  photo_suite_followup: "套图后续",
  sight_failure: "视频理解失败",
  video: "视频",
  video_failure: "视频生成失败",
  video_followup: "视频后续",
};

export const LIFE_DECISION_KIND_LABELS = {
  daily_plan: "日程规划",
  weekly_plan: "周计划",
  outfit: "穿搭判断",
  invite: "邀约判断",
  invite_outfit: "邀约穿搭",
  proactive_reply: "闲时回复",
  proactive_decision: "闲时回复裁定",
  state: "状态刷新",
  review: "复盘",
  other: "其他决策",
};

export const WEEK_PROGRESS_STATUS_LABELS = {
  done: "已生成",
  missing: "暂无记录",
  empty: "无时间轴",
};

export const PAGE_STATUS_REASON_LABELS = {
  state: "实时状态更新",
  daily_refresh: "每日生活背景刷新",
  nightly_review: "夜间复盘",
  weekly_refresh: "周计划刷新",
  weather: "天气更新",
  memo: "备忘录更新",
  autonomous_life_update: "自主生活状态与穿搭更新",
  chat_state_refresh: "聊天触发状态巡检",
  timeline_execution: "时间轴执行状态更新",
  invite_outfit_update: "邀约后的穿搭判断",
  outfit_update: "穿搭更新",
  private_revisit: "私聊回访",
  proactive_reply: "闲时回复",
  proactive_reply_decision: "闲时回复裁定",
  expression_decision: "表达方式裁定",
  chat_memory: "聊天记忆更新",
  daily_generation_searching: "正在搜索日程参考",
  daily_generation_waiting: "等待日程生成",
  daily_generation_generating: "正在生成日程",
  daily_generation_completed: "日程生成完成",
  daily_generation_failed: "日程生成失败",
};

export const VISIBILITY_LABELS = {
  unseen: "未看见",
  scanned: "扫到",
  seen_but_ignored: "看见但略过",
  seen: "已留意",
  focused: "重点留意",
  skimmed: "粗略看过",
  ignored: "已忽略",
  missed: "未注意",
};

export const FRESHNESS_LABELS = {
  fresh: "新鲜",
  recent: "较近",
  stale: "过期",
  old: "旧消息",
  reactivated: "重新激活",
  renewed: "重新变新",
  ignored: "已忽略",
  seen: "已看见",
  unknown: "未知",
};

export const PREFERENCE_CATEGORY_LABELS = {
  activity: "活动",
  outfit: "穿搭",
  hair: "发型",
  social: "社交",
  sleep: "睡眠",
  place: "地点",
  style: "风格",
  other: "其他",
  general: "综合",
};

export const MEMORY_ENTITY_TYPE_LABELS = {
  topic: "话题",
  person: "人物",
  place: "地点",
  event: "事件",
  preference: "偏好",
  constraint: "约束",
  correction: "纠偏",
};

export const MEMORY_CONFLICT_TYPE_LABELS = {
  tension: "记忆张力",
  temporary_tension: "临时冲突",
  override: "覆盖修正",
};

export const LONG_TERM_MEMORY_CATEGORY_LABELS = {
  general: "综合记忆",
  life: "生活记忆",
  evidence: "证据记忆",
  chat_summary: "会话摘要",
  episode: "生活片段",
  feedback: "行为反馈",
  expression: "表达记忆",
  correction: "记忆纠偏",
  short_term: "短期记忆",
  preference: "偏好",
};

export const EMOJI_EMOTION_CATEGORY_LABELS = {
  happy: "开心",
  sad: "难过",
  angry: "生气",
  neutral: "平静",
};

export const TARGET_TYPE_LABELS = {
  topic: "话题",
  user: "用户",
  person: "人物",
  relationship: "关系",
  group: "群聊",
  session: "会话",
  message: "消息",
  action: "动作",
  behavior: "行为",
  place: "地点",
  event: "事件",
  life_event: "生活事件",
  life_episode: "生活片段",
  life_decision: "生活决策",
  life_adjustment: "生活纠偏",
  action_decision: "动作裁定",
  proactive_session: "闲时回复会话",
  chat_summary: "会话摘要",
  group_environment: "群聊环境",
  message_visibility: "消息留意",
  focus: "关注目标",
  focus_target: "关注目标",
  daily: "每日记录",
  daily_plan: "日程规划",
  schedule: "日程安排",
  activity: "活动",
  outfit: "穿搭",
  sleep: "睡眠",
  social: "社交",
  style: "风格",
  state: "状态",
  memory: "记忆",
  preference: "偏好",
  review: "复盘",
  commitment: "未来承诺",
  term: "语言",
  boundary: "记忆边界",
  other: "其他",
};

export const EVIDENCE_TYPE_LABELS = {
  observation: "观察证据",
  daily_generation: "每日生成依据",
  episode: "生活片段证据",
  chat_memory: "聊天记忆证据",
  relationship: "关系证据",
  behavior_feedback: "行为反馈证据",
  focus_target: "关注目标证据",
  correction: "修正证据",
  decision: "决策证据",
  feedback: "反馈证据",
  instruction: "指令证据",
  proactive_reply: "闲时回复证据",
  review: "复盘证据",
  manual: "手动记录",
  memory: "记忆证据",
  source: "来源证据",
  other: "其他证据",
};

export const PLACE_TYPE_LABELS = {
  place: "地点",
  home: "家",
  residence: "居住地",
  anchor: "主要地点",
  cafe: "咖啡店",
  bookstore: "书店",
  shop: "商店",
  mall: "商场",
  school: "学校",
  office: "办公室",
  workplace: "工作地点",
  park: "公园",
  transit: "交通点",
  neighborhood: "附近街区",
  street: "街道",
  restaurant: "餐厅",
  cinema: "影院",
  gallery: "展馆",
  museum: "展馆",
  gym: "健身场所",
  library: "图书馆",
  other: "其他地点",
};

export const EMOJI_SOURCE_LABELS = {
  manual: "手动导入",
  review: "识图收集",
  verified: "识图确认",
  trusted: "平台表情",
  plain_image: "普通图片",
};

export const EMOJI_STATUS_LABELS = {
  ready: "可用",
  pending: "待识别",
  reviewing: "待确认",
  rejected: "已拒绝",
  missing: "缺失",
  failed: "失败",
  disabled: "已停用",
};

export const EMOJI_TYPE_LABELS = {
  emoji: "表情",
  face: "系统表情",
  mface: "商城表情",
  sticker: "贴纸",
  custom_emoji: "自定义表情",
  customemoji: "自定义表情",
  market_face: "商城表情",
  marketface: "商城表情",
  wechat_emoji: "微信表情",
  wechatemoji: "微信表情",
  is_emoji: "表情",
  is_sticker: "贴纸",
  emoji_image: "表情图片",
  sticker_image: "贴纸图片",
  mface_image: "商城表情图片",
  market_face_image: "商城表情图片",
  marketface_image: "商城表情图片",
  reaction: "反应",
  meme: "梗图",
  other: "其他",
  image: "图片",
};

export const SCOPE_LABELS = {
  global: "全局",
  general: "通用",
  group: "群聊",
  private: "私聊",
  session: "会话",
  user: "用户",
  relationship: "关系",
  topic: "话题",
  memory: "记忆",
  current_group: "当前群聊",
  current_session: "当前会话",
  current: "当前",
  short_term: "短期",
  long_term: "长期",
  correction: "纠偏",
  other: "其他",
};

export const HEALTH_CHECK_LABELS = {
  episodes: "生活片段",
  evidence: "证据链",
  focus: "关注目标",
  feedback: "行为反馈",
  emotion_arcs: "情绪脉络",
  physiological_rhythm_logs: "生理节律",
  terms: "语言",
  boundaries: "记忆边界",
  relationships: "关系档案",
  places: "地点档案",
  events: "事件记忆",
  chat_summaries: "会话摘要",
  group_environments: "群聊环境",
  message_visibility: "消息留意",
  action_decisions: "动作裁定",
  life_episodes: "生活片段",
  life_decisions: "生活决策",
  memory_evidence: "证据链",
  memory_corrections: "记忆纠偏",
  behavior_feedback: "行为反馈",
  emotion_arcs: "情绪脉络",
  physiological_rhythm_logs: "生理节律",
  reply_effects: "回复效果",
  focus_targets: "关注目标",
  focus_slots: "关注槽位",
  life_terms: "语言",
  memory_boundaries: "记忆边界",
  memory_rows: "记忆存储",
  memory_maintenance: "记忆维护",
  preferences: "长期偏好",
  life_events: "生活事件",
  relationship_contacts: "关系联系",
  expression_profiles: "表达画像",
  expression_reviews: "表达复盘",
  expression_intents: "表达意图",
  behavior_patterns: "行为模式",
  behavior_scenes: "行为场景",
  session_mid_summaries: "会话中段摘要",
  temporary_expression_states: "临时表达状态",
  emoji_assets: "表情素材",
  video_insights: "视频理解",
  video_insight_details: "视频理解明细",
  video_insight_frames: "视频理解帧",
  review_preferences: "复盘偏好",
};

export const STORAGE_CATEGORY_LABELS = {
  daily: "日常记录",
  memory: "世界记忆",
  planning: "计划安排",
  review: "日常复盘",
};

export const RHYTHM_LIFECYCLE_LABELS = {
  transient: "临时",
  short_term: "短期",
  sustained: "持续",
  active: "进行中",
  expired: "已过期",
};

export const EVENT_STATUS_LABELS = {
  open: "进行中",
  pending: "待进行",
  planned: "已计划",
  scheduled: "已计划",
  active: "进行中",
  in_progress: "进行中",
  done: "已完成",
  completed: "已完成",
  skipped: "已跳过",
  closed: "已关闭",
  canceled: "已取消",
  cancelled: "已取消",
  expired: "已过期",
  superseded: "已被替代",
};

export const EPISODE_KIND_LABELS = {
  daily: "每日",
  daily_plan: "日程规划",
  chat: "聊天",
  group: "群聊",
  relationship: "关系",
  outing: "外出",
  decision: "决策",
  mood: "心情",
  other: "其他",
};

export const EPISODE_STATUS_LABELS = {
  open: "进行中",
  done: "已完成",
  closed: "已关闭",
  cancelled: "已取消",
  expired: "已过期",
  corrected: "已修正",
  active: "进行中",
  superseded: "已被替代",
};

export const BOUNDARY_POLICY_LABELS = {
  allow: "允许",
  deny: "禁止",
  ask: "谨慎询问",
};

export const FEEDBACK_RESULT_LABELS = {
  positive: "正向",
  neutral: "中性",
  negative: "负向",
  unknown: "未知",
};

export const ACTION_LABELS = {
  ignore: "忽略",
  reply: "回复",
  observe: "观察",
  remember: "记录",
  save: "保存",
  save_memory: "保存记忆",
  skip_memory: "跳过记忆",
  need_deep_analysis: "需要深度分析",
  voice_expression: "表达方式：语音",
  text_expression: "表达方式：文字",
  deep_analysis: "深度分析",
  watch: "观察",
  watch_only: "仅观察",
  skim: "扫读",
  reactivate: "重新激活",
  defer: "延后",
  comfort: "安抚",
  push_back: "反驳",
  join_ritual: "跟仪式",
  eat_melon: "吃瓜围观",
  interrupt: "打断",
  no_reply: "不回复",
  proactive_reply: "闲时回复",
  private_revisit: "私聊回访",
  regular_reply: "普通回复",
  previous_reply: "上一轮回复",
  proactive_observe: "随心观察",
  proactive_wait: "随心等待",
  proactive_skip: "随心略过",
  none: "无动作",
};

export const UNDERSTANDING_LABELS = {
  understood: "已理解",
  partial: "部分理解",
  unclear: "不明确",
  unknown: "未知",
};

export const SCENE_TYPE_LABELS = {
  chat: "普通闲聊",
  casual: "普通闲聊",
  casual_chat: "普通闲聊",
  profile: "群友档案",
  relationship: "群友档案",
  group_profile: "群友档案",
  environment: "群环境",
  group_environment: "群环境",
  invite: "邀约线索",
  invitation: "邀约线索",
  conflict: "争论",
  argument: "争论",
  meme: "玩梗",
  joke: "玩梗",
  welcome: "欢迎",
  spam: "刷屏",
  repetition: "复读",
  eat_melon: "吃瓜",
  discussing_bot: "提到我",
  other: "其他",
};

export const BOT_WATCH_STATE_LABELS = {
  blackout: "未关注",
  peek: "偶尔看一眼",
  skim_window: "窗口扫读",
  active_watch: "持续关注",
  engaged: "已参与",
};

export const INTERRUPT_LEVEL_LABELS = {
  ordinary: "普通消息可打断",
  medium: "中等相关才打断",
  high: "强信号才打断",
};

export const ATMOSPHERE_LABELS = {
  quiet: "冷清",
  calm: "平稳",
  normal: "平稳",
  active: "活跃",
  busy: "活跃",
  spam: "刷屏",
  argument: "争论",
  conflict: "争论",
  meme: "玩梗",
  joke: "玩梗",
  welcome: "欢迎",
  other: "其他",
};

export const STORAGE_TABLE_LABELS = {
  days: "每日记录",
  timelines: "时间轴",
  outfit_history: "穿搭历史",
  day_meta: "生活标签",
  states: "实时状态",
  state_logs: "状态日志",
  day_places: "当日地点",
  day_events: "当日事件",
  day_event_people: "事件人物",
  relationships: "关系档案",
  relationship_notes: "关系备注",
  relationship_points: "关系记忆点",
  relationship_contacts: "关系联系",
  places: "地点档案",
  events: "事件记忆",
  event_people: "事件人物",
  chat_summaries: "会话摘要",
  chat_summary_people: "摘要人物",
  group_environments: "群聊环境",
  message_visibility: "消息留意",
  action_decisions: "动作裁定",
  preferences: "长期偏好",
  reply_effects: "回复效果",
  life_decisions: "生活决策",
  memory_corrections: "记忆纠偏",
  expression_profiles: "表达画像",
  expression_reviews: "表达复盘",
  expression_intents: "表达意图",
  behavior_patterns: "行为模式",
  behavior_scenes: "行为场景",
  session_mid_summaries: "会话中段摘要",
  temporary_expression_states: "临时表达状态",
  focus_slots: "关注槽位",
  emoji_assets: "表情素材",
  video_insights: "视频理解",
  video_insight_details: "视频理解明细",
  video_insight_frames: "视频理解帧",
  life_events: "生活事件",
  life_episodes: "生活片段",
  life_episode_people: "片段人物",
  life_episode_places: "片段地点",
  memory_evidence: "记忆证据",
  behavior_feedback: "行为反馈",
  focus_targets: "关注目标",
  physiological_rhythm_logs: "生理节律",
  life_terms: "语言",
  memory_boundaries: "记忆边界",
  memory_maintenance: "记忆维护",
  week_plans: "周计划",
  week_goals: "周目标",
  week_hints: "周提示",
  week_suggestions: "周建议",
  commitments: "未来承诺",
  commitment_people: "承诺人物",
  day_commitments: "当日承诺",
  daily_reviews: "每日复盘",
  daily_review_points: "复盘要点",
  review_preferences: "复盘偏好",
};
